# Generated by Django 5.2.9 on 2026-01-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['display_order', 'created_at']},
        ),
        migrations.AddField(
            model_name='course',
            name='button_text',
            field=models.CharField(default='Enroll Now', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='course',
            name='duration_text',
            field=models.CharField(default='30 days', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='plan_type',
            field=models.CharField(choices=[('free_trial', 'Free Trial'), ('paid_trial', 'Paid Trial'), ('regular', 'Regular Plan'), ('neet_complete', 'NEET Complete Program'), ('other', 'Other')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
