# Generated by Django 5.2.6 on 2025-12-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teammember",
            name="team_name",
            field=models.CharField(
                choices=[
                    ("FOUNDERS", "Founders"),
                    ("SUPER_MENTORS", "Super Mentors"),
                    ("TECH", "Tech Team"),
                    ("DESIGN", "Design Team"),
                    ("MARKETING", "Marketing Team"),
                ],
                default="TECH",
                max_length=50,
            ),
        ),
    ]
