# Generated by Django 5.2.6 on 2025-12-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0002_teammember_team_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperMentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("expertise", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("photo", models.ImageField(upload_to="super_mentors/")),
            ],
        ),
        migrations.AlterField(
            model_name="teammember",
            name="team_name",
            field=models.CharField(
                choices=[
                    ("FOUNDERS", "Founders"),
                    ("SUPER_MENTORS", "Super Mentors"),
                    ("TECH", "Tech Team"),
                    ("DESIGN", "Design Team"),
                    ("MARKETING", "Marketing Team"),
                ],
                max_length=50,
            ),
        ),
    ]
