# Generated by Django 5.2.6 on 2025-12-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0003_supermentor_alter_teammember_team_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SuperMentor",
        ),
    ]
