# Generated by Django 5.2.9 on 2026-01-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_delete_supermentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team_name',
            field=models.CharField(choices=[('FOUNDERS', 'Founders'), ('SUPER_MENTORS', 'Super Mentors'), ('MENTORS', 'Mentors')], max_length=50),
        ),
    ]
