# Generated by Django 5.2.9 on 2026-01-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team", "0005_alter_teammember_team_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teammember",
            name="team_name",
            field=models.CharField(
                choices=[
                    ("FOUNDERS", "Founders"),
                    ("SUPER_MENTORS", "Super Mentors"),
                    ("MENTORS", "Mentors"),
                    ("TECH_TEAM", "Tech Team"),
                ],
                max_length=50,
            ),
        ),
    ]
