# Generated by Django 5.2.9 on 2026-01-23 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='days_to_neet',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mentor_assigned',
            field=models.CharField(default='Dr. Sharma', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mentor_qualification',
            field=models.CharField(default='MBBS, AIIMS', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='neet_exam_date',
            field=models.DateField(default='2025-05-05'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='attempt_year',
            field=models.IntegerField(default=2025),
        ),
    ]
