# Generated by Django 5.2.9 on 2026-01-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_studentprofile_days_to_neet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mentor_photos/')),
                ('qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
