# Generated by Django 5.2.9 on 2026-01-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_mentor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='mentor_assigned',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mentor_qualification',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.mentor'),
        ),
    ]
