# Generated by Django 5.2.9 on 2026-01-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_studentprofile_mentor_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
