# Generated by Django 5.2.9 on 2026-01-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_studentprofile_company_id_studentprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='mentor_company_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
