# Generated by Django 5.2.9 on 2026-01-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_studentprofile_mentor_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='company_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
