# Generated by Django 5.2.9 on 2026-01-28 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_studentgoal_studentprogress_testscore_studylog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PYQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology')], max_length=50)),
                ('year', models.CharField(choices=[('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], max_length=4)),
                ('topic', models.CharField(choices=[('Mechanics', 'Mechanics'), ('Optics', 'Optics'), ('Thermodynamics', 'Thermodynamics'), ('Electromagnetism', 'Electromagnetism'), ('Modern Physics', 'Modern Physics'), ('Waves', 'Waves'), ('Electronics', 'Electronics'), ('Organic Chemistry', 'Organic Chemistry'), ('Inorganic Chemistry', 'Inorganic Chemistry'), ('Physical Chemistry', 'Physical Chemistry'), ('Coordination Compounds', 'Coordination Compounds'), ('Biomolecules', 'Biomolecules'), ('Environmental Chemistry', 'Environmental Chemistry'), ('Human Physiology', 'Human Physiology'), ('Plant Physiology', 'Plant Physiology'), ('Genetics', 'Genetics'), ('Ecology', 'Ecology'), ('Cell Biology', 'Cell Biology'), ('Biotechnology', 'Biotechnology'), ('Reproduction', 'Reproduction')], max_length=100)),
                ('question_number', models.IntegerField()),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=500)),
                ('option_b', models.CharField(max_length=500)),
                ('option_c', models.CharField(max_length=500)),
                ('option_d', models.CharField(max_length=500)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'subject', 'question_number'],
            },
        ),
    ]
