# Generated by Django 5.2.9 on 2026-01-30 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_mentor_user_studentprofile_mentor_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorprofile",
            name="meet_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
