# Generated by Django 5.2.9 on 2026-02-04 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_studentmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='message_replies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dashboard.studentmessage')),
                ('replied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_replies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Reply',
                'verbose_name_plural': 'Message Replies',
                'ordering': ['created_at'],
            },
        ),
    ]
