# Generated by Django 5.2.6 on 2025-12-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuperMentor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("expertise", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("photo", models.ImageField(upload_to="super_mentors/")),
            ],
        ),
    ]
