# Generated by Django 5.2.6 on 2025-12-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0003_emailotp_delete_registeruser"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="emailotp",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
