# Generated by Django 5.2.7 on 2026-01-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_emailotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
