# Generated by Django 5.2.9 on 2026-01-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_emailotp_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supermentor',
            options={'verbose_name': 'Mentor & Super Mentor', 'verbose_name_plural': 'Mentor & Super Mentor'},
        ),
        migrations.AddField(
            model_name='supermentor',
            name='designation',
            field=models.CharField(choices=[('mentor', 'Mentor'), ('super_mentor', 'Super Mentor')], default='mentor', max_length=20),
        ),
    ]
