# Generated by Django 5.2.9 on 2026-01-29 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboard", "0014_mentor_user_studentprofile_mentor_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[("normal", "Normal"), ("academic", "Academic")],
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("completed", "Completed"),
                            ("missed_student", "Missed by Student"),
                            ("missed_mentor", "Missed by Mentor"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mentor_calls",
                        to="dashboard.mentorprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_calls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MentorScheduleConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weekday_start", models.TimeField()),
                ("weekday_end", models.TimeField()),
                ("sunday_morning_start", models.TimeField(blank=True, null=True)),
                ("sunday_morning_end", models.TimeField(blank=True, null=True)),
                ("sunday_evening_start", models.TimeField(blank=True, null=True)),
                ("sunday_evening_end", models.TimeField(blank=True, null=True)),
                ("dinner_start", models.TimeField(blank=True, null=True)),
                ("dinner_end", models.TimeField(blank=True, null=True)),
                ("gap_minutes", models.IntegerField(default=5)),
                (
                    "mentor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_config",
                        to="dashboard.mentorprofile",
                    ),
                ),
            ],
        ),
    ]
